# Day 2 of Data Science Training by Mr. Harshit Dawar

## For Loop

In [1]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [3]:
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


In [5]:
for i in range(10, 1, -1):
    print(i)

10
9
8
7
6
5
4
3
2


In [14]:
a = [10,9,1,2,3,4,5,6,9]

In [15]:
len(a)

9

In [8]:
for i in a:
    print(i, end = " ")

1 2 3 4 5 

In [9]:
for i in range(a):
    print(i)
    

TypeError: 'list' object cannot be interpreted as an integer

In [13]:
for i in range(len(a)):
    print(i + 1, end = " ")

1 2 3 4 5 6 7 8 9 

## While Loop

In [22]:
z = 0

In [23]:
while z < 10:
    if z == 5:
        break
    print(z)
    z = z + 1

0
1
2
3
4


In [26]:
a = 0

In [27]:
while True:
    if a == 10:
        break
    print(a)
    a += 1 # => a = a + 1
    #a -= 1 # a = a - 1

0
1
2
3
4
5
6
7
8
9


In [29]:
for i in range(20):
    print(i, end = " ")
    i += 5

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [39]:
i = 20

In [40]:
while i > 0:
    if i > 20:
        break
    print(i, end = " ")
    i -= 2

20 18 16 14 12 10 8 6 4 2 

## Data Science Part Begins from Here

In [42]:
import numpy as np

In [43]:
array1 = np.array([1,2,3,4,5])

In [44]:
type(array1)

numpy.ndarray

In [51]:
array2 = np.array([1,2,3,4,5])

In [52]:
array2

array([1, 2, 3, 4, 5])

In [49]:
array1

array([1, 2, 3, 4, 5])

In [53]:
array1 + array2

array([ 2,  4,  6,  8, 10])

In [54]:
a = np.array([1,2,3])

b = np.array([ 
                [1,2,3],
                 [4,5,6]
            ])

In [55]:
a + b

array([[2, 4, 6],
       [5, 7, 9]])

In [56]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [57]:
b.ndim

2

In [58]:
a.ndim

1

In [59]:
b.shape

(2, 3)

In [60]:
# Need to be explained a.shape

(3,)

In [61]:
b.size

6

In [62]:
a.size

3

In [74]:
b[  1:, 1: ]

array([[5, 6]])

In [75]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
c = np.full((3,3), 1)

In [88]:
c.dtype

dtype('int64')

In [90]:
a,b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [89]:
np.add(a, b)

array([[2, 4, 6],
       [5, 7, 9]])

In [91]:
np.subtract(a,b)

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [93]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [94]:
np.divide(a,b)

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [97]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [101]:
np.arange(1, 10, 5)

array([1, 6])

In [102]:
example_list = []

for i in range(100000):
    example_list.append(i)

In [106]:
numpy_example_list = np.arange(0,100000)

In [107]:
type(numpy_example_list), type(example_list)

(numpy.ndarray, list)

In [108]:
%timeit sum(example_list)

710 µs ± 41 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [109]:
# 0.000710 seconds

In [111]:
%timeit np.sum(numpy_example_list)

58.2 µs ± 1.96 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [112]:
np.sqrt(25)

5.0

In [113]:
a, b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [114]:
a < b

array([[False, False, False],
       [ True,  True,  True]])

## Random Number in numpy

In [125]:
np.random.seed(1)
np.random.randint(1,15, size = (5,5))

array([[ 6, 12, 13,  9, 10],
       [12,  6,  1,  1,  2],
       [13,  8, 14, 13,  7],
       [10,  3,  5,  6,  3],
       [ 5, 12, 13, 11, 13]])

In [133]:
np.random.seed(5)
np.random.random(size=(5,5))

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

## Slicing in numpy n - dim arrays!

In [134]:
ndim_array_example = np.random.randint(1,15, size = (3,3))

In [135]:
ndim_array_example

array([[ 5,  5, 10],
       [ 4, 12,  3],
       [ 5,  7, 10]])

In [138]:
ndim_array_example[ 2:, 1:2 ]

array([[7]])

In [140]:
ndim_array_example[ 2:3, 1: ]

array([[ 7, 10]])

In [146]:
ndim_array_example[1:2, 2:3] + ndim_array_example[1:2, 0:1]

array([[7]])

## Reshaping the Array


In [148]:
a

array([1, 2, 3])

In [147]:
a.shape

(3,)

In [152]:
a = a.reshape((1,3))

In [153]:
a.shape

(1, 3)

In [154]:
a

array([[1, 2, 3]])

In [155]:
a, b

(array([[1, 2, 3]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [156]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [157]:
a1 = np.random.randint(1, 3, size = (2,2))

In [158]:
a1

array([[2, 2],
       [1, 2]])

In [162]:
a = 5
b = 6

In [163]:
a, b

(5, 6)

In [164]:
a, b = b, a

In [165]:
a, b

(6, 5)

In [166]:
a1, b1  = np.random.randint(1, 3, size = (2,5)), np.random.randint(1, 3, size = (2,5))

In [167]:
a1, b1

(array([[2, 2, 1, 1, 2],
        [1, 1, 2, 2, 2]]),
 array([[1, 2, 2, 2, 2],
        [1, 2, 2, 2, 2]]))

In [168]:
a1.dot(b1)

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

In [169]:
a1.shape

(2, 5)

In [170]:
b1.shape

(2, 5)

In [171]:
a1.dot(b1.reshape((5,2)))

array([[14, 15],
       [15, 14]])

In [173]:
a1.dot(b1.T)

array([[14, 14],
       [15, 15]])

In [176]:
b1.T

array([[1, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [179]:
b1.reshape((5,2))

array([[1, 2],
       [2, 2],
       [2, 1],
       [2, 2],
       [2, 2]])

In [180]:
b1

array([[1, 2, 2, 2, 2],
       [1, 2, 2, 2, 2]])

## Sorting an array

In [174]:
a1.sort()

In [175]:
a1

array([[1, 1, 2, 2, 2],
       [1, 1, 2, 2, 2]])

## Data Loading using numpy

In [197]:
data = np.loadtxt("rp.txt", dtype = "str", delimiter=",")

In [198]:
data

array(['Generally',
       ' solution to Travelling Salesman Problem(TSP) using any algorithm results only in a single path which is optimal path according the algorithm. This can be sometimes not the best path for the user',
       ' because it is possible that the user wants to visit any other city first irrespective of some increase in cost for the travelling route. So',
       ' the proposed algorithm for the TSP will display all the possible paths in a given scenario with their respective costs using dynamic programming. Based on the cost and user preference',
       ' a user can select any of the path displayed.'], dtype='<U195')

## Pandas

In [199]:
import pandas as pd

### Series Data Types in Pandas

In [201]:
example_pandas_series = pd.Series(["Data", "Science", "Training"])

In [203]:
type(example_pandas_series)

pandas.core.series.Series

In [209]:
example_pandas_series2 = pd.Series(["Data", "Science", "Training"], index=["D", "S", "T"])

In [210]:
example_pandas_series2

D        Data
S     Science
T    Training
dtype: object

In [206]:
type(example_pandas_series2)

pandas.core.series.Series

In [212]:
colours = pd.Series(["Red", "Green", "Yellow"])
cars = pd.Series(["Lambo", "Audi", "BMW"])

### DataFrames Data Types in Pandas

In [224]:
example_dataframe = pd.DataFrame([1,2,3,4,5], index=["1","2","3","4","5"], columns = ["Values"])

In [225]:
example_dataframe

Values
1       1
2       2
3       3
4       4
5       5

In [226]:
example_dataframe2 = pd.DataFrame({"colour":colours, "cars":cars})

In [227]:
example_dataframe2

colour   cars
0     Red  Lambo
1   Green   Audi
2  Yellow    BMW